CREATE TABLE MATRICULAS(
  ID_ESTUDANTE NUMBER NOT NULL,
  ID_CURSO NUMBER NOT NULL,
  MEDIAALUNO FLOAT(16),
  FOREIGN KEY(ID_ESTUDANTE) REFERENCES ESTUDANTES(ID),
  FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID)
  )
 
 